# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.4.6
_src_path: gh:epics-containers/ioc-template
description: Generic IOC for Amtron CM100 series power supplies for laser diodes.
git_platform: github.com
github_org: TAUSystems
name: ioc-amtron-cm100
repo_uri: git@github.com:TAUSystems/ioc-amtron-cm100.git
rtems: false
